version: '3.8'

services:
  app:
    build: .
    container_name: doctor-review-bot
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://doctor_user:doctor_pass@db:5432/doctor_review
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - FACEBOOK_ACCESS_TOKEN=${FACEBOOK_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - doctor-review-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: doctor-review-db
    environment:
      - POSTGRES_USER=doctor_user
      - POSTGRES_PASSWORD=doctor_pass
      - POSTGRES_DB=doctor_review
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - doctor-review-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doctor_user -d doctor_review"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  doctor-review-network:
    driver: bridge
